-- Insertar actividades económicas de ejemplo para el sistema tributario
-- Estas se guardan en mayúsculas para normalización

INSERT INTO actividades_economicas (codigo, descripcion, aplica_iva) VALUES
('ACT000001', 'VENTA AL POR MENOR DE PRODUCTOS ALIMENTICIOS', true),
('ACT000002', 'SERVICIOS DE CONSULTORÍA EMPRESARIAL', true),
('ACT000003', 'CONSTRUCCIÓN DE EDIFICIOS RESIDENCIALES', true),
('ACT000004', 'TRANSPORTE TERRESTRE DE CARGA', true),
('ACT000005', 'SERVICIOS DE CONTABILIDAD Y AUDITORÍA', true),
('ACT000006', 'VENTA AL POR MENOR DE ROPA Y CALZADO', true),
('ACT000007', 'SERVICIOS DE RESTAURANTE Y COMIDA RÁPIDA', true),
('ACT000008', 'SERVICIOS DE REPARACIÓN DE VEHÍCULOS', true),
('ACT000009', 'SERVICIOS DE BELLEZA Y PELUQUERÍA', true),
('ACT000010', 'VENTA AL POR MENOR DE MEDICAMENTOS', true),
('ACT000011', 'SERVICIOS DE EDUCACIÓN PRIVADA', false),
('ACT000012', 'SERVICIOS MÉDICOS Y ODONTOLÓGICOS', false),
('ACT000013', 'AGRICULTURA Y GANADERÍA', true),
('ACT000014', 'SERVICIOS DE SEGURIDAD PRIVADA', true),
('ACT000015', 'VENTA AL POR MENOR DE ELECTRODOMÉSTICOS', true),
('ACT000016', 'SERVICIOS DE LIMPIEZA Y MANTENIMIENTO', true),
('ACT000017', 'VENTA AL POR MAYOR DE PRODUCTOS VARIOS', true),
('ACT000018', 'SERVICIOS DE DISEÑO GRÁFICO Y PUBLICIDAD', true),
('ACT000019', 'SERVICIOS DE HOSPEDAJE Y TURISMO', true),
('ACT000020', 'SERVICIOS DE TELECOMUNICACIONES', true);

-- Verificar la inserción
SELECT * FROM actividades_economicas ORDER BY codigo;
